; Program: Random32 Demo
; Purpose: Demonstrate the use of Random32 from Irvine32 library
INCLUDE Irvine32.inc

.data
    prompt BYTE "Random numbers generated by Random32:", 0
    newline BYTE 0Dh, 0Ah, 0

.code
main PROC
    call ClrScr                 ; Clear the console screen
    mov edx, OFFSET prompt      ; Load the address of the prompt message
    call WriteString            ; Display the prompt
    call CrLf
    call Randomize              ; Initialize the random number generator

    mov ecx, 0Ah
generate_random:
    call Random32               ; Generate a random 32-bit number
    call WriteDec               ; Display the random number as a decimal
    call CrLf                   ; Move to the next line
    loop generate_random        ; Repeat until counter reaches 0

    call WaitMsg                ; Wait for user input before exiting
    call ExitProcess            ; Exit the program
main ENDP

END main
